

export const FETCH_POSTS_BEGIN   = 'FETCH_POSTS_BEGIN';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const SELECT_POST = 'SELECT_POST';
export const CREATE_POST = 'CREATE_POST'
export const SEARCH_POSTS = 'SEARCH_POSTS';
